apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: coreproclaimapi-autoscaler
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: coreproclaimapi-deployment
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
